Windows: Add a missing WINAPI for a callback function
This fixes compilation for i686 after
5feefd30734cd12753956819fc7c152be07c24cd, fixing compilation errors
like these:

    qtbase/src/plugins/platforms/windows/qwindowswindow.cpp:901:69: error: no matching member function for call to 'registerWindowClass'
      901 |     const QString windowTitlebarName = QWindowsContext::instance()->registerWindowClass(QStringLiteral("_q_titlebar"), WndProcTitleBar, CS_VREDRAW|CS_HREDRAW, nullptr, false);
          |                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
    qtbase/src/plugins/platforms/windows/qwindowscontext.h:77:13: note: candidate function not viable: no known conversion from 'LRESULT (HWND, UINT, WPARAM, LPARAM)' (aka 'long (HWND__ *, unsigned int, unsigned int, long)') to 'WNDPROC' (aka 'long (*)(HWND__ *, unsigned int, unsigned int, long) __attribute__((stdcall))') for 2nd argument
       77 |     QString registerWindowClass(QString cname, WNDPROC proc,
          |             ^                                  ~~~~~~~~~~~~

Change-Id: I9eb2d3dc0626b8606d4b49cf82fba34d6a4b2942
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@qt.io>